clientIO/appmixer-connectors

- src/appmixer/redmine/bundle.json
- src/appmixer/redmine/core/IssueCreate/component.json
- src/appmixer/redmine/core/IssueDelete/component.json
- src/appmixer/redmine/core/IssueShow/component.json
- src/appmixer/redmine/core/IssueUpdate/component.json
- src/appmixer/redmine/core/IssuesList/component.json
- src/appmixer/redmine/core/ProjectsList/component.json
- src/appmixer/redmine/openapi.yml
Fixes for https://github.com/clientIO/appmixer-components/issues/1586#issuecomment-1916140346
> Redmine: Update component descriptions, id description and examples for custom_fields

- src/appmixer/naxai/bundle.json
- src/appmixer/naxai/openapi.yml
- src/appmixer/naxai/people/PutContact/PutContact.js
Fix for https://github.com/clientIO/appmixer-components/issues/1662#issuecomment-1970281620
> Improve tooltips in PutContact.js

- src/appmixer/google/drive/NewFile/NewFile.js
- src/appmixer/google/drive/NewFile/component.json
- src/appmixer/google/drive/bundle.json
- src/appmixer/google/drive/drive-commons.js
- src/appmixer/google/drive/module.json
port of the https://github.com/clientIO/appmixer-components/pull/1696
- `processedFiles` preventing duplicities - checking if the file hasn't been processed already in last 3 pagetokens
tested on QA (https://my.qa.appmixer.com/designer/95920319-1836-4adb-a79d-a2785375603c/88f79df7-c4c2-4609-b33f-1ee2f6dec424)
- upload 4 files in parallel on start 
- upload 200 files manually in the Gdrive ui
- once the NewFile is triggered, it uploads the file into Appmixer files
results: 208 dummy files has been uploaded 
- small_dummy_996 - 999 - uploaded using the uploadFile on flow start -
- newFile has been triggered 4x (small_dummy_996 - 999 ) + 200x for after the manual upload within gdrive => total 208 small_dummy files:
> Google.Drive: NewFile update

- src/appmixer/naxai/bundle.json
- src/appmixer/naxai/openapi.yml
- src/appmixer/naxai/people/GetContactsIdentifier/component.json
Reported in https://github.com/clientIO/appmixer-components/issues/1662#issuecomment-1996272472
The out parameter of "Get Contacts Identifier" action is returning `undefined` label for identifier variable.
> Naxai: fix identifier property

- src/appmixer/utils/controls/OnError/OnError.js
- src/appmixer/utils/controls/OnError/component.json
- Handled pagination with `searchAfter` ( Appmixer 6.0 introduces a new query parameter `searchAfter`)
- Used locks to handle a large number of logs.
- https://github.com/clientIO/appmixer-components/issues/1466
original PR https://github.com/clientIO/appmixer-components/pull/1690
> util.controls.onError: use SearchAfter  - port from the https://github.com/clientIO/appmixer-components/pull/1690

- src/appmixer/jira/bundle.json
- src/appmixer/jira/issues/CreateIssue/component.json
- src/appmixer/jira/issues/ListField/ListField.js
- src/appmixer/jira/issues/ListField/component.json
- src/appmixer/jira/issues/UpdateIssue/component.json
- src/appmixer/jira/jira-commons.js
Issue: https://github.com/clientIO/appmixer-components/issues/1748
Reason: The value of `autoCompleteUrl` for `labels` field is incorrect (see [here](https://community.developer.atlassian.com/t/autocompleteurl-in-editmeta-of-some-fields/36667) and [here](https://community.developer.atlassian.com/t/how-to-filter-labels-based-on-query-or-project-in-rest-api-3/73536))
> JIRA: Fix labels in inspector for `CreateIssue` and `UpdateIssue`

- src/appmixer/zendesk/auth.js
- src/appmixer/zendesktickets/auth.js
- src/appmixer/zendesktickets/bundle.json
- src/appmixer/zendesktickets/lib.js
- src/appmixer/zendesktickets/service.json
new config `globalKeys` 
when truthy, `pre` renders the input for the `subdomain` only, otherwise renders `clientId`, `clientSecret` and `subdomain`
> Zendesk chat: authentication using global keys 

- src/appmixer/shopify/CustomerDataRequest.js
- src/appmixer/shopify/CustomerRedactRequest.js
- src/appmixer/shopify/ShopRedactRequest.js
- src/appmixer/shopify/package.json
- src/appmixer/shopify/plugin.js
- src/appmixer/shopify/routes.js
```
POST [APPMIXER_API]/plugins/appmixer/shopify/customers/data_request
POST [APPMIXER_API]/plugins/appmixer/shopify/customers/redact
POST [APPMIXER_API]/plugins/appmixer/shopify/shop/redact
```
-  **HOW TO TEST**
- the endpoint above are public try to post some data:
- customers/data_request: [sample payload](https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-redact-payload)
- customers/redact: [sample payload](https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#customers-redact-payload)
- shop/redact: [sample payload](https://shopify.dev/docs/apps/webhooks/configuration/mandatory-webhooks#shop-redact)
```
GET [APPMIXER_API]/plugins/appmixer/shopify/customers/data_request
GET [APPMIXER_API]/plugins/appmixer/shopify/customers/redact
GET …
```
> Shopify: support for mandatory webhooks

- src/appmixer/xero/accounting/NewContact/NewContact.js
- src/appmixer/xero/accounting/NewContact/component.json
- src/appmixer/xero/accounting/NewInvoice/NewInvoice.js
- src/appmixer/xero/accounting/NewInvoice/component.json
- src/appmixer/xero/accounting/UpdatedContact/UpdatedContact.js
- src/appmixer/xero/accounting/UpdatedContact/component.json
- src/appmixer/xero/accounting/UpdatedInvoice/UpdatedInvoice.js
- src/appmixer/xero/accounting/UpdatedInvoice/component.json
- src/appmixer/xero/accounting/quota.js
- src/appmixer/xero/bundle.json
- src/appmixer/xero/commons.js
- src/appmixer/xero/plugin.js
- src/appmixer/xero/routes.js
Issue: https://github.com/clientIO/appmixer-components/issues/1763
- we must process webhook payload "as is" (without parsing it as JSON) because the signature is for content that is not exactly `JSON.stringify(payload)`, see https://devblog.xero.com/keeping-your-integration-in-sync-implementing-xero-webhooks-using-node-express-and-ngrok-6d2976baac6d
- Xero splits the payload events randomly (for example for a 100 contacts imported from CSV). Sometimes it is 100 messages at once, sometimes split into eg 18 and 82.
- using optimized data retrieval: https://devblog.xero.com/new-filtering-on-the-accounting-api-b8acee14ec25
- webhook component gets list of `resourceId` for each event (eg Contact)
- retrieve Contacts by batches of 40 (for 200 contacts it is 5 HTTP requests instead of 200) …
> Xero triggers

- src/appmixer/utils/controls/OnError/OnError.js
- src/appmixer/utils/controls/OnError/component.json
- src/appmixer/utils/controls/bundle.json
- Handled pagination with `searchAfter` ( Appmixer 6.0 introduces a new query parameter `searchAfter`)
- Used locks to handle a large number of logs.
- https://github.com/clientIO/appmixer-components/issues/1466
original PR https://github.com/clientIO/appmixer-components/pull/1690
> util.controls.onError: use SearchAfter

- src/appmixer/xero/accounting/CreateInvoice/CreateInvoice.js
- src/appmixer/xero/accounting/CreateInvoice/component.json
- src/appmixer/xero/accounting/UpdateInvoice/UpdateInvoice.js
- src/appmixer/xero/accounting/UpdateInvoice/component.json
- src/appmixer/xero/bundle.json
Fix for: https://github.com/clientIO/appmixer-components/issues/1763#issuecomment-2090469658
Only a log message appeared. No error message even though it failed on JSON parsing
> Xero: fix LineItems parsing for Invoices 

- src/appmixer/quickbooks/auth.js
- src/appmixer/quickbooks/bundle.json
To be able to immediately identify `realmId` (i.e. QBO instance) when viewing a flow. A single QB account can have multiple realms. Some of them might be sandbox companies.
To get Realm ID of QBO instance, go to https://app.qbo.intuit.com/app/homepage?locale=en-us -> ⚙️ (top right) -> Additional info
> Quickbooks: Add `realmid` to account description

- src/appmixer/utils/csv/AddRows/AddRows.js
- src/appmixer/utils/csv/AddRows/component.json
- src/appmixer/utils/csv/CSVProcessor.js
- src/appmixer/utils/csv/bundle.json
- src/appmixer/utils/csv/quota.js
> Q2: Is it possible to replace the "Rows" text box with a text area that includes a scroll bar? I experimented with a large number of rows, approximately 700, and noticed that the text box isn't suitable for this purpose.
https://github.com/clientIO/appmixer-components/issues/1769#issuecomment-2100691470 
fixes:
> utils.csv.AddRows:  use textarea for the rows

- src/appmixer/utils/csv/AddRow/AddRow.js
- src/appmixer/utils/csv/AddRows/AddRows.js
- src/appmixer/utils/csv/AddRows/component.json
- src/appmixer/utils/csv/CSVProcessor.js
- src/appmixer/utils/csv/CreateInspector/CreateInspector.js
- src/appmixer/utils/csv/bundle.json
- CSVProcessor.addRows: 
- remove dummy `closure` 
- refactor working with streams
- AddRows component 
- remove `withHeaders` - this input was ignored anyway  (https://github.com/clientIO/appmixer-connectors/pull/106/files#diff-589b5c64d7c756bc5cacb1ddc4ba51cc520ed7d79d46e99d4eb4d515b8e3a034L17)
- fix resolving `withHeaders` property
> utils.csv: AddRow fix

- src/appmixer/snowflake/bundle.json
- src/appmixer/snowflake/package.json
Fix for https://github.com/clientIO/appmixer-components/issues/1813
```
jirihofman@Jiri-MacBook-Pro AddRow % node 
Welcome to Node.js v18.18.2.
Type ".help" for more information.
> require('./AddRow')
Uncaught TypeError: Object.setPrototypeOf called on null or undefined
at setPrototypeOf (<anonymous>)
at inherits (node:util:260:3)
at Object.<anonymous> (/Users/jirihofman/prace/clientio/appmixer-connectors/src/appmixer/snowflake/node_modules/snowflake-sdk/lib/agent/https_proxy_ocsp_agent.js:89:1)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require …
```
> Snowflake SDK update

- src/appmixer/utils/xml/JsonToXml/JsonToXml.js
- src/appmixer/utils/xml/bundle.json
input 
```
{"car":[{"color":"blue"},{"color":"black"}]}
```
is causing error
> utils.XML: fix the input when the input JSON is string

- src/appmixer/trello/bundle.json
- src/appmixer/trello/checklist/AddChecklistToCard/component.json
- src/appmixer/trello/checklist/ListCardChecklists/component.json
- src/appmixer/trello/list/AddLabelToCard/component.json
- src/appmixer/trello/list/CreateCard/CreateCard.js
- src/appmixer/trello/list/CreateCard/component.json
Fix for https://github.com/clientIO/appmixer-components/issues/1801#issuecomment-2270984892
It should be clear that there are two ways to use `Board` and `Card` inputs
1. Static
- Select a Board (eg Welcome).
- Select a Card. The list contains only cards for the selected board.
2. Dynamic
- Don't select a Board.
- Don't select a Card (clicking on the input)
- Pick a variable into a Card field (using plus icon)
> Trello update

- src/appmixer/google/bigquery/CreateInspector/component.json
> google.bigquery: remove redundant scopes

- src/appmixer/system/bundle.json
follow-up for the 
- https://github.com/clientIO/appmixer-connectors/pull/137
Added the engine dependency as multiple urls for the `WEBHOOK_FLOW_COMPONENT_ERROR` is supported from the the 6.1
> system.OnAnyComponentError: add engine dependency

- src/appmixer/facebookbusiness/package.json
We want to have package versions locked. Discovered in https://github.com/clientIO/appmixer-components/actions/runs/10571123923/job/29286698458
> Facebook businesss lock dependencies

- src/appmixer/google/gmail/AddLabelsToEmail/component.json
- src/appmixer/google/gmail/CreateDraft/component.json
- src/appmixer/google/gmail/DeleteLabel/component.json
- src/appmixer/google/gmail/FindEmails/component.json
- src/appmixer/google/gmail/GetAttachment/component.json
- src/appmixer/google/gmail/RemoveLabelFromEmail/component.json
- src/appmixer/google/gmail/bundle.json
Made fields required and improved tooltips in 
- AddLabelsToEmail
- CreateDraft
- FindEmails
- GetAttachment
- RemoveLabelsFromEmail
Updated bundle.json
- Includes the latest version for auth.js, findEmails (showing limit only when output type is NOT "first") and above changes
> Google.gmail updates - Tooltips, Marking Fields Required, Bundle.json update

- src/appmixer/jira/bundle.json
- src/appmixer/jira/issues/ListField/ListField.js
Updated the ListField code to fix the endpoint that fetches the list of reporters to fix issue with JIRA API scopes when obtaining reporters.
> Jira (bug fix) Issue with scopes when obtaining reporters for Create Issue

- src/appmixer/utils/controls/Digest/Digest.js
- src/appmixer/utils/controls/Digest/component.json
- src/appmixer/utils/controls/Digest/package-lock.json
- src/appmixer/utils/controls/Digest/package.json
- src/appmixer/utils/controls/ListTimeZones/ListTimeZones.js
- src/appmixer/utils/controls/ListTimeZones/component.json
- src/appmixer/utils/controls/ListTimeZones/timezones.json
- src/appmixer/utils/controls/bundle.json
> utils.controls.Digest

- src/appmixer/google/bigquery/DeletedRow/DeletedRow.js
- src/appmixer/google/bigquery/DeletedRow/component.json
- src/appmixer/google/bigquery/ListProjects/ListProjects.js
- src/appmixer/google/bigquery/NewRow/NewRow.js
- src/appmixer/google/bigquery/NewRow/component.json
- src/appmixer/google/bigquery/UpdatedRow/UpdatedRow.js
- src/appmixer/google/bigquery/UpdatedRow/component.json
- src/appmixer/google/bigquery/bundle.json
- src/appmixer/google/bigquery/common.js
In the Triggers NewRow, UpdatedRow and DeletedRow
The SQL Query needs project ID. which was being fetched using a function getProjectId. In this function we were trying to find the project ID out of a list of all projects as whichever projects numericid would match the first part of clientID, we would take that project's projectID.
This approach was not working as none of the projects' numeric ID was matching anything in the list of projects
Hence, now an input field of select type has been introduced in the triggers which helps the user to select one project out of all the projects in their bigQuery playground and then the query is run on this project's ID.
> Google.Bigquery.(patch update).Fix for error "Cannot read properties of undefined (reading 'id')"

- src/appmixer/notion/bundle.json
- src/appmixer/notion/core/CreateDatabaseItem/CreateDatabaseItem.js
- src/appmixer/notion/core/CreateDatabaseItem/component.json
- src/appmixer/notion/core/FindDatabaseItem/FindDatabaseItem.js
- src/appmixer/notion/core/FindDatabaseItem/component.json
- src/appmixer/notion/core/NewDatabaseItem/component.json
- src/appmixer/notion/core/UpdateDatabaseItem/UpdateDatabaseItem.js
- src/appmixer/notion/core/UpdateDatabaseItem/component.json
the database ID was originally an input field, allowing users to pass values via tags or variables from previous components. However, since these values only resolve at design time, we couldn’t generate the inspector dynamically, meaning the dependent input fields for that database wouldn't appear.
To resolve this, I changed the database ID from an input port field to a property field, so it now only displays a dropdown of databases, preventing the issue of unresolved tags or variables at design time and ensuring proper inspector generation.
> Notion.Create/Update/Find Database Item. (Patch) Converting databaseId inputs to properties

- src/appmixer/google/gmail/CreateDraft/component.json
- src/appmixer/google/gmail/ListSignatures/ListSignatures.js
- src/appmixer/google/gmail/bundle.json
If an Alias existed without a signature, then it's email address would show but the signature wont have any value. So the label in the dropdown of signatures select field would show the email address but behind it there wouldnt be any value. 
This was causing a breakage.
Since David's account had multiple aliases and some had signatures and some didnt, this was discovered. 
This has been fixed by checking the alias, if it has a signature, only then we work with it's signature
> Gmail.ListSignatures.CreateDraft (patch update) Fix for signatures dropdown input field

- src/appmixer/trello/bundle.json
- src/appmixer/trello/list/AddLabelToCard/AddLabelToCard.js
- src/appmixer/trello/list/AddLabelToCard/component.json
"Updated the list of colors in color-palette of AddLabelToCard component and updated the tooltip texts and description"
The issue https://github.com/clientIO/appmixer-components/issues/1940
> Trello.AddLabelToCard (minor) Updated list of colors

- src/appmixer/slack/bundle.json
`NewUserWebhook` is a new trigger using Slack Events Subscription. It requires additional permission granted in Slack App configuration.
Without this change Slack will not send any messages to `/plugins/appmixer/slack/events`
> Slack update changelog

- src/appmixer/google/calendar/ListEvents/component.json
- src/appmixer/google/calendar/bundle.json
A private component ListCalendards had bugs, the path to source endpoint was wrong which was listing calendars to be selected in the inspector
> Google.Calendar.ListEvents (patch) Bug fixes

- src/appmixer/hubspot/BaseSubscriptionComponent.js
- src/appmixer/hubspot/bundle.json
- src/appmixer/hubspot/commons.js
- src/appmixer/hubspot/crm/DeletedContact/DeletedContact.js
- src/appmixer/hubspot/crm/NewContact/NewContact.js
- src/appmixer/hubspot/crm/NewDeal/NewDeal.js
- src/appmixer/hubspot/crm/UpdatedContact/UpdatedContact.js
- src/appmixer/hubspot/crm/UpdatedDeal/UpdatedDeal.js
- src/appmixer/hubspot/routes.js
see https://github.com/clientIO/appmixer-components/issues/1700#issuecomment-2437420148
> Hubspot (patch) trigger fixes

- src/appmixer/monday/bundle.json
- src/appmixer/monday/core/AddFileToUpdate/component.json
- src/appmixer/monday/core/GetItem/GetItem.js
- src/appmixer/monday/queries.js
fixes for https://github.com/clientIO/appmixer-connectors/issues/265
1. Seems like there was a mistake in the way we were fetching the title of item as according to this article it is further layered https://community.monday.com/t/title-of-column-in-new-api/65575
I have hence fixed the query that fetches the item and it should work now
2. I have added the filepicker option in AddFileToUpdate component. It should work as well
> Monday.com GetItem/AddFileToUpdate (Major) Bug fixes

- src/appmixer/activecampaign/bundle.json
- src/appmixer/activecampaign/contacts/UpdateContact/UpdateContact.js
- src/appmixer/activecampaign/deals/CreateDeal/component.json
- src/appmixer/activecampaign/deals/UpdateDeal/UpdateDeal.js
- src/appmixer/activecampaign/deals/UpdateDeal/component.json
- src/appmixer/activecampaign/quota.js
- src/appmixer/activecampaign/tasks/CreateTask/component.json
The UpdateDeal component requires for Deal amount to be filled, however as this is update component, it shouldn't be required on our side. My current workaround is the GET deal/dealId for the original amount and then either use it or send the new value.
> ActiveCampaign (patch) multiple components fixes

- src/appmixer/smartsheet/bundle.json
- src/appmixer/smartsheet/core/CopyFolder/component.json
- src/appmixer/smartsheet/core/CopySheet/component.json
- src/appmixer/smartsheet/core/MoveRows/component.json
- src/appmixer/smartsheet/core/UpdateFolder/UpdateFolder.js
- src/appmixer/smartsheet/core/UpdateFolder/component.json
In input fields like "include" the input is being taken as "select" but it should be multiselect. It is fixed https://github.com/clientIO/appmixer-components/issues/1938#issuecomment-2519401350
> Smartsheet CopyFolder/MoveFolder (patch) Updating select to multiselect in inspector

- src/appmixer/microsoft/sharepoint/GetFile/GetFile.js
- src/appmixer/microsoft/sharepoint/ListSites/ListSites.js
- src/appmixer/microsoft/sharepoint/ListSites/component.json
- src/appmixer/microsoft/sharepoint/MoveFileOrFolder/MoveFileOrFolder.js
- src/appmixer/microsoft/sharepoint/MoveFileOrFolder/component.json
There are reported issues in 4 components:
In multiple of them there was reported error "Circular reference" I found out that it is from the _onedrive-api_ library, so I had to change the components to using REST API, affected components:
**ListSites**
**GetFile**
**MoveFileOrFolder** (currenly returns an error when the move is successful)
**DownloadFile** and **GetFile** are reported to trigger multiple times for 1 file, I couldn't replicate this issue
> Microsoft.SharePoint (minor) moving from onedrive API in some components

- src/appmixer/mssql/bundle.json
- src/appmixer/mssql/db/Query/Query.js
- src/appmixer/mssql/db/Query/component.json
The component encountered an error (`TypeError: queryResponse.recordset is not iterable`) when executing non-`SELECT` queries like `INSERT`, `UPDATE`, or `DELETE`. This happened because such queries do not return a `recordset`, and the code incorrectly assumed its presence, leading to runtime failures. https://github.com/clientIO/appmixer-components/issues/2020
1. **Conditional Handling for `recordset`:**
- Added a check to handle scenarios where the `recordset` is absent (for non-`SELECT` queries).
- Non-`SELECT` queries now rely on `rowsAffected` to report the results.
2. **Improved Output Logic:**
- Ensured that `rowsAffected` is sent as output for non-`SELECT` queries.
- Preserved the handling of `recordset` for `SELECT` queries.
- Prevents errors when running non-`SELECT` queries.
> MsSql (patch) Fix for Non SELECT Queries

- src/appmixer/xero/accounting/NewContact/NewContact.js
- src/appmixer/xero/accounting/NewInvoice/NewInvoice.js
- src/appmixer/xero/accounting/UpdatedContact/UpdatedContact.js
- src/appmixer/xero/accounting/UpdatedInvoice/UpdatedInvoice.js
- src/appmixer/xero/bundle.json
- src/appmixer/xero/routes.js
Fix for Issue 3 in https://github.com/clientIO/appmixer-components/issues/2019#issuecomment-2513522119
- this allows the triggers to work for all hosted tenants without any Xero app configuration
> Xero (patch) triggers use AuthHub

- src/appmixer/google/spreadsheets/bundle.json
follow-up for the https://github.com/clientIO/appmixer-connectors/pull/182 
change introduced in the https://github.com/clientIO/appmixer-connectors/pull/182 is breaking therefore the version should be 4. However, as the version 3.0.0 is not released yet, we can include the changes from the https://github.com/clientIO/appmixer-connectors/pull/182 into the version 3.0.1
> Google.spreadsheets: update release notes

- src/appmixer/utils/tasks/RequestApprovalEmail/RequestApprovalEmail.js
- src/appmixer/utils/tasks/bundle.json
Fix for https://github.com/clientIO/appmixer-components/issues/1999#issuecomment-2566093171 - issue 2
The duplicate tasks were created because Appmixer retried the failed component runs of `RequestApprovalEmail`. Even thou it failed, the POST actions to create tasks were run before it, thus creating the tasks.
On properly configured environment this is not a problem. This can happen on a self-hosted instance without `PEOPLE_TASKS_DASHBOARD_URL` ENV.
> Tasks (patch) - fix no config duplicates

- src/appmixer/smartsheet/bundle.json
- src/appmixer/smartsheet/core/CopyFolder/component.json
- src/appmixer/smartsheet/core/MoveFolder/component.json
MoveFolder was showing transformation related error as properties were not defined in the component.json
CopyFolder did not have DestinationType marked required although it is marked required by the smartSheet API
> Smartsheet Movefolder Copyfolder (patch) Bug Fixes

- src/appmixer/microsoft/sharepoint/NewFile/NewFile.js
- src/appmixer/microsoft/sharepoint/bundle.json
Comparing the object for folder and file I have noticed, that when it is a file, it has "file" property, when a folder, it has "folder" property. The component now returns only objects with "file" property.
> Microsoft.Sharepoint (patch) NewFile triggers for files only

- src/appmixer/microsoft/sharepoint/NewFile/component.json
I have checked documentation of the API: https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=javascript and haven't found a way or mention of how to make the trigger trigger for sub-folders. Updated the tooltip to make it clear.
> Microsoft.Sharepoint.NewFile: update toolitp

- src/appmixer/hubspot/bundle.json
- src/appmixer/hubspot/crm/NewContact/NewContact.js
- src/appmixer/hubspot/crm/NewDeal/NewDeal.js
- src/appmixer/hubspot/crm/UpdatedContact/UpdatedContact.js
- src/appmixer/hubspot/crm/UpdatedDeal/UpdatedDeal.js
Fixes https://github.com/clientIO/appmixer-components/issues/1700#issuecomment-2573312483
The problem is that HubSpot can send the same event more than once
> Hubspot (patch) handle duplicate events

- src/appmixer/microsoft/dynamics/ListAccounts/ListAccounts.js
- src/appmixer/microsoft/dynamics/ListContacts/ListContacts.js
- src/appmixer/microsoft/dynamics/ListLeads/ListLeads.js
Fixes https://github.com/clientIO/appmixer-components/issues/1670
The removed code was not triggered because all three components call `DynamicEntity` to generate outputPortOptions. 
ListContacts/component.json (and other 2)
```json
{
"name": "out",
"source": {
"url": "/component/appmixer/microsoft/dynamics/DynamicEntity?outPort=out",
"data": {
"messages": {
"in/logicalName": "contact",
"in/outputType": "inputs/in/outputType"
},
"properties": {
"generateOutputPortOptions": true
}
}
}
},
```
There is no code that would trigger `return this.getOutputPortOptions(context, outputType);`, therefore no bundle bump. It is just refactoring and will get released with future updates.
> Microsoft Dynamics (fix) remove unused code

- src/appmixer/slack/bundle.json
- src/appmixer/slack/list/NewChannelMessageRT/NewChannelMessageRT.js
- src/appmixer/slack/list/NewUserWebhook/NewUserWebhook.js
- src/appmixer/slack/routes.js
Closes https://github.com/clientIO/appmixer-components/issues/1979
Slack docs: https://api.slack.com/authentication/verifying-requests-from-slack#validating-a-request
> Slack (major) add webhook payload verification

- src/appmixer/cloudflare/bundle.json
- src/appmixer/cloudflare/lists/AddToIPList/component.json
- when `min` is define, it's not possible to input a value - it always immediately jumps back to `60`
> Cloudflare lists: fix ttl

- src/appmixer/microsoft/excel/ListColumns/component.json
- src/appmixer/microsoft/excel/ListSheets/ListSheets.js
- src/appmixer/microsoft/excel/bundle.json
ListSheets was showing an error `400 - {"error":{"code":"invalidRequest","message":"A potentially dangerous Request.Path value was detected from the client (*).","innerError":{"code":"badArgument","date":"2025-02-11T07:47:16","request-id":"be848855-85fb-495a-b815-0511a4833590","client-request-id":"be848855-85fb-495a-b815-0511a4833590"}}}` 
Which was because of an asterisk * used in the query endpoint.
Then, in the ListColumns (used for output tags of NewRow) there was no source attached to the Sheets input field hence error in this component as well
> Microsoft.Excel.NewRow (Patch) Bugs Fixed

- src/appmixer/openai/bundle.json
- src/appmixer/openai/core/createEdit/component.json
- src/appmixer/openai/core/createEdit/createEdit.js
Fixes https://github.com/clientIO/appmixer-components/issues/2159
`CreateEdit` is deprecated alongside the recommended models for it. See https://platform.openai.com/docs/deprecations#edit-models-endpoint
> OpenAI (patch) deprecate CreateEdit

- src/appmixer/raynet/auth.js
- src/appmixer/raynet/bundle.json
- src/appmixer/raynet/raynet-commons.js
According to [Raynet API doc](https://app.raynet.cz/api/doc/) the only method to authenticate (still using Basic) is using email and API key associated (generated in raynet admin section) with the account for the email. So the change drops the support for password which was no longer working anyways. 
Bumping version to 1.0.2
After this change I have packed/published this new version to my appmixer tenant and tested all the components from this connector.
> Raynet API is no longer supporting authentication using password
