- src/appmixer/hubspot/auth.js
- src/appmixer/hubspot/bundle.json
- src/appmixer/hubspot/crm/CreateContact/component.json
- src/appmixer/hubspot/crm/GetContact/GetContact.js
- src/appmixer/hubspot/crm/GetContact/component.json
- src/appmixer/hubspot/engagements/CreateEmail/CreateEmail.js
- src/appmixer/hubspot/engagements/CreateEmail/component.json
- src/appmixer/hubspot/engagements/GetEmails/GetEmails.js
- src/appmixer/hubspot/engagements/GetEmails/component.json
- src/appmixer/hubspot/package.json
- add new component: Engagements - GetEmails (/crm/v3/objects/emails/batch/read)
https://developers.hubspot.com/docs/api/crm/email
- update GetContact
- fix support for adding properties 
- add support for associations
> Hubspot engagements

- src/appmixer/redmine/bundle.json
- src/appmixer/redmine/core/IssueCreate/component.json
- src/appmixer/redmine/core/IssueDelete/component.json
- src/appmixer/redmine/core/IssueShow/component.json
- src/appmixer/redmine/core/IssueUpdate/component.json
- src/appmixer/redmine/core/IssuesList/component.json
- src/appmixer/redmine/core/ProjectsList/ProjectsList.js
- src/appmixer/redmine/core/ProjectsList/component.json
- src/appmixer/redmine/core/ProjectsList/transform.js
- src/appmixer/redmine/openapi.yml
Fixes for https://github.com/clientIO/appmixer-components/issues/1586#issuecomment-1905359350
- Fixed by adding a `source` for `project_id` in `FindIssues`, `CreateIssue`, `UpdateIssue`
- Removed `Example: 1` and similar
> redmine: fixes

- src/appmixer/ringring/bundle.json
- src/appmixer/ringring/core/MessageApiSmsRequest_Post/component.json
- src/appmixer/ringring/openapi.yml
Fix for https://github.com/clientIO/appmixer-components/issues/1661#issuecomment-1945406875
> RingRing: fix outports

- src/appmixer/microsoft/plugin.js
For https://github.com/clientIO/appmixer-fe/issues/3970
> redirectUri

- src/appmixer/google/drive/CopyFile/component.json
- src/appmixer/google/drive/CreateFolder/component.json
- src/appmixer/google/drive/DeleteFileOrFolder/component.json
- src/appmixer/google/drive/DownloadFile/component.json
- src/appmixer/google/drive/ExportFile/component.json
- src/appmixer/google/drive/FindFileOrFolder/component.json
- src/appmixer/google/drive/GetFile/component.json
- src/appmixer/google/drive/ListFiles/component.json
- src/appmixer/google/drive/NewFile/component.json
- src/appmixer/google/drive/UploadFile/component.json
- src/appmixer/google/drive/quota.js
- https://github.com/clientIO/appmixer-components/issues/1709
> Google Drive: add quota

- src/appmixer/utils/controls/SetVariable/SetVariable.js
- src/appmixer/utils/controls/bundle.json
- https://github.com/clientIO/appmixer-components/issues/1725
> utils.controls.SetVariable: remove isValidType check

- src/appmixer/google/drive/drive-commons.js
- src/appmixer/google/gmail/GetAttachment/GetAttachment.js
- debug: related to the https://appmixer.freshdesk.com/a/tickets/8909
> google: drive.NewFile, drive.MoveOrUpdateFolder - debug is `false` by default

- src/appmixer/google/drive/CreateFolder/CreateFolder.js
- src/appmixer/google/drive/CreateFolder/component.json
- src/appmixer/google/drive/FindFileOrFolder/FindFileOrFolder.js
- src/appmixer/google/drive/FindFileOrFolder/component.json
- src/appmixer/google/drive/UploadFile/UploadFile.js
- src/appmixer/google/drive/UploadFile/component.json
- src/appmixer/google/drive/bundle.json
- src/appmixer/google/drive/drive-commons.js
> fix: google.drive: name contains special chars

- src/appmixer/kafka/common.js
- src/appmixer/kafka/config.js
- src/appmixer/kafka/connections.js
- src/appmixer/kafka/jobs.js
- src/appmixer/kafka/package.json
- src/appmixer/kafka/platform/NewMessage/NewMessage.js
- src/appmixer/kafka/platform/NewMessage/component.json
- src/appmixer/kafka/platform/SendMessage/SendMessage.js
- src/appmixer/kafka/platform/SendMessage/component.json
- src/appmixer/kafka/plugin.js
- src/appmixer/kafka/routes.js
- kafka.NewMessage:  Added plugins to maintain a persistent Kafka connection until server restart or flow stoppage.
> Plugin approach: kafka connector

- src/appmixer/kafka/bundle.json
- src/appmixer/kafka/platform/NewMessage/component.json
- src/appmixer/kafka/platform/SendMessage/component.json
duplicate of the 
- https://github.com/clientIO/appmixer-connectors/pull/91
> kafka: update tooltips

- src/appmixer/utils/controls/OnError/OnError.js
- src/appmixer/utils/controls/OnError/component.json
- src/appmixer/utils/controls/bundle.json
duplicate of
- https://github.com/clientIO/appmixer-connectors/pull/84
> Utils.control.onerror

- src/appmixer/microsoft/onedrive/OneDrivePicker/OneDrivePicker.js
- src/appmixer/microsoft/onedrive/OneDrivePicker/component.json
- src/appmixer/microsoft/onedrive/bundle.json
Fix: Added new redirectUri to OneDrivePicker controller so its passed into the new change in the picker input component
> OneDrive: Add redirectUri to Picker Component

- src/appmixer/azuredocumentintelligence/README.md
- src/appmixer/azuredocumentintelligence/auth.js
- src/appmixer/azuredocumentintelligence/bundle.json
- src/appmixer/azuredocumentintelligence/classifiers/ClassifyDocument/ClassifyDocument.js
- src/appmixer/azuredocumentintelligence/classifiers/ClassifyDocument/component.json
- src/appmixer/azuredocumentintelligence/classifiers/ListClassifiers/ListClassifiers.js
- src/appmixer/azuredocumentintelligence/classifiers/ListClassifiers/component.json
- src/appmixer/azuredocumentintelligence/lib.js
- src/appmixer/azuredocumentintelligence/package-lock.json
- src/appmixer/azuredocumentintelligence/package.json
- src/appmixer/azuredocumentintelligence/quota.js
- src/appmixer/azuredocumentintelligence/service.json
Issue: https://github.com/clientIO/appmixer-components/issues/1778
Components: `ListClassifiers` and `ClassifyDocument`
Flow that classifies Hearthstone card (passed as URL to its image).
Log for `ClassifyDocument`
> Azure Document Intelligence

- src/appmixer/google/spreadsheets/CountRows/component.json
- src/appmixer/google/spreadsheets/CreateRow/component.json
- src/appmixer/google/spreadsheets/DeleteRows/component.json
- src/appmixer/google/spreadsheets/FindRow/component.json
- src/appmixer/google/spreadsheets/GetRows/component.json
- src/appmixer/google/spreadsheets/ListColumns/component.json
- src/appmixer/google/spreadsheets/ListColumnsWithSelectInputs/ListColumnsWithSelectInputs.js
- src/appmixer/google/spreadsheets/ListColumnsWithSelectInputs/component.json
- src/appmixer/google/spreadsheets/ListRows/component.json
- src/appmixer/google/spreadsheets/ListSheets/ListSheets.js
- src/appmixer/google/spreadsheets/ListWorksheets/component.json
- src/appmixer/google/spreadsheets/NewRow/component.json
- src/appmixer/google/spreadsheets/UpdatedRow/component.json
- src/appmixer/google/spreadsheets/bundle.json
- src/appmixer/google/spreadsheets/package.json
> Google.sheets: remove legacy scope

- src/appmixer/zendesktickets/auth.js
- src/appmixer/zendesktickets/bundle.json
- fix when the `globalKeys` is set to `false`
> Zendesk tickets - fix global auth keys

- src/appmixer/calendly/bundle.json
- src/appmixer/calendly/events/InviteeCanceled/component.json
- src/appmixer/calendly/events/InviteeCreated/component.json
Allows answer values to be easily obtained w/o extra transformation/extraction
> Calendly - Provide friendly access to first 3 answers of custom questions

- src/appmixer/azuredocumentintelligence/bundle.json
- src/appmixer/azuredocumentintelligence/lib.js
Fix for https://github.com/clientIO/appmixer-components/issues/1778#issuecomment-2174915088 - Issue 1
> azuredocumentintelligence: add missing path module

- src/appmixer/azuredocumentintelligence/bundle.json
- src/appmixer/azuredocumentintelligence/lib.js
Fix for https://github.com/clientIO/appmixer-components/issues/1778#issuecomment-2179838984
> azuredocumentintelligence: stringify object when exporting to csv

- src/appmixer/slack/bundle.json
- src/appmixer/slack/files/GetFile/component.json
- src/appmixer/slack/files/UploadFile/UploadFile.js
- src/appmixer/slack/files/UploadFile/component.json
Fixes for https://github.com/clientIO/appmixer-components/issues/1580#issuecomment-2228065994
- update tooltips for GetFile and UploadFile
- use v2 parameters in UploadFile
> Slack fixes for GetFile, UploadFile

- src/appmixer/slack/bundle.json
- src/appmixer/slack/files/UploadFile/component.json
> Update UploadFile file ID tooltip

- src/appmixer/jotform/bundle.json
- src/appmixer/jotform/core/DeleteForm/component.json
- src/appmixer/jotform/core/GetFormSubmission/component.json
- src/appmixer/jotform/core/GetFormSubmissions/component.json
- src/appmixer/jotform/core/GetUser/component.json
- src/appmixer/jotform/core/GetUserForms/component.json
- src/appmixer/jotform/core/GetUserReports/component.json
- src/appmixer/jotform/core/NewFormSubmission/component.json
ticket: https://appmixer.freshdesk.com/a/tickets/9017
> Jotform: remove blank quota definition

- src/appmixer/asana/bundle.json
- src/appmixer/asana/tasks/CreateSubtask/component.json
- src/appmixer/asana/tasks/CreateTask/component.json
- src/appmixer/asana/tasks/ListUsers/ListUsers.js
- src/appmixer/asana/tasks/UpdateTask/component.json
- follow-up for the https://github.com/clientIO/appmixer-connectors/pull/132 (added changelog)
> Asana: fix assignee dynamic input

- src/appmixer/kafka/bundle.json
- src/appmixer/kafka/connections.js
https://github.com/clientIO/appmixer-components/issues/1815#issuecomment-2233189875
> Kafka: fix acks=0

- src/appmixer/utils/ftp/CreateDirectory/CreateDirectory.js
- src/appmixer/utils/ftp/DownloadFile/DownloadFile.js
- src/appmixer/utils/ftp/GetFileInfo/GetFileInfo.js
- src/appmixer/utils/ftp/List/List.js
- src/appmixer/utils/ftp/NewFile/NewFile.js
- src/appmixer/utils/ftp/RemoveDirectory/RemoveDirectory.js
- src/appmixer/utils/ftp/RemoveFile/RemoveFile.js
- src/appmixer/utils/ftp/RenameFile/RenameFile.js
- src/appmixer/utils/ftp/UploadFile/UploadFile.js
- src/appmixer/utils/ftp/auth.js
- src/appmixer/utils/ftp/bundle.json
- src/appmixer/utils/ftp/client.js
We were in need of a key option in the FTP component.
This is the implementation i came up with.
I have tested it  that it still works with password and the new key option.
Let me know if there are things you would like to see different or changed.
> added support for private keys in the ftp component

- src/appmixer/airtable/bundle.json
- src/appmixer/airtable/records/ListBases/ListBases.js
- src/appmixer/airtable/records/ListTables/ListTables.js
> airtable: rename ListBases array output variable from Array to Bases

- src/appmixer/slack/bundle.json
- src/appmixer/slack/list/ListUsers/ListUsers.js
- src/appmixer/slack/list/ListUsers/component.json
- src/appmixer/slack/list/ListUsers/transformers.js
- src/appmixer/slack/messages/SendDirectMessage/SendDirectMessage.js
- src/appmixer/slack/messages/SendDirectMessage/component.json
- src/appmixer/slack/slack-commons.js
Issue: https://github.com/clientIO/appmixer-components/issues/1812
- `ListUsers`
- `SendPrivateMessage`
> Slack: add Direct messaging

- src/appmixer/slack/bundle.json
- src/appmixer/slack/files/UploadFileToUser/UploadFileToUser.js
- src/appmixer/slack/files/UploadFileToUser/component.json
Some stuff that I forgot to commit in #159
> Slack: fix UploadFileToUser

- src/appmixer/facebookbusiness/auth.js
- src/appmixer/facebookbusiness/bundle.json
- src/appmixer/facebookbusiness/marketing/AddMemberToAudience/AddMemberToAudience.js
- src/appmixer/facebookbusiness/marketing/AddMemberToAudience/component.json
- src/appmixer/facebookbusiness/marketing/AddMembersFromCSVToAudience/AddMembersFromCSVToAudience.js
- src/appmixer/facebookbusiness/marketing/AddMembersFromCSVToAudience/component.json
- src/appmixer/facebookbusiness/marketing/CreateAudience/CreateAudience.js
- src/appmixer/facebookbusiness/marketing/CreateAudience/UpdateAudience.js
- src/appmixer/facebookbusiness/marketing/CreateAudience/component.json
- src/appmixer/facebookbusiness/marketing/DeleteAudience/DeleteAudience.js
- src/appmixer/facebookbusiness/marketing/DeleteAudience/GetCustomAudience.js
- src/appmixer/facebookbusiness/marketing/DeleteAudience/component.json
- src/appmixer/facebookbusiness/marketing/GetAdAccounts/GetAdAccounts.js
- src/appmixer/facebookbusiness/marketing/GetAdAccounts/UpdateAudience.js
- src/appmixer/facebookbusiness/marketing/GetAdAccounts/component.json
- src/appmixer/facebookbusiness/marketing/GetCampaigns/GetCampaigns.js
- src/appmixer/facebookbusiness/marketing/GetCampaigns/component.json
- src/appmixer/facebookbusiness/marketing/GetCustomAudiences/GetCustomAudiences.js
- src/appmixer/facebookbusiness/marketing/GetCustomAudiences/UpdateAudience.js
- src/appmixer/facebookbusiness/marketing/GetCustomAudiences/component.json
- src/appmixer/facebookbusiness/marketing/UpdateAudience/UpdateAudience.js
- src/appmixer/facebookbusiness/marketing/UpdateAudience/component.json
- src/appmixer/facebookbusiness/package.json
- src/appmixer/facebookbusiness/quota.js
- src/appmixer/facebookbusiness/service.json
> facebookbusiness

- src/appmixer/google/gmail/AddLabelsToEmail/component.json
- src/appmixer/google/gmail/CreateDraft/component.json
- src/appmixer/google/gmail/DeleteEmail/component.json
- src/appmixer/google/gmail/FindEmails/FindEmails.js
- src/appmixer/google/gmail/FindEmails/component.json
- src/appmixer/google/gmail/GetEmail/component.json
- src/appmixer/google/gmail/ListAttachments/component.json
- src/appmixer/google/gmail/ListEmails/ListEmails.js
- src/appmixer/google/gmail/MarkEmailAsRead/component.json
- src/appmixer/google/gmail/MarkEmailAsUnread/component.json
- src/appmixer/google/gmail/MoveEmail/component.json
- src/appmixer/google/gmail/NewEmail/component.json
- src/appmixer/google/gmail/NewStarredEmail/component.json
- src/appmixer/google/gmail/RemoveLabelFromEmail/component.json
- src/appmixer/google/gmail/ReplyToEmail/component.json
- src/appmixer/google/gmail/SendEmail/component.json
- src/appmixer/google/gmail/bundle.json
This PR includes the following changes
1. Removal of the Email messages from the input dropdown from all related components
2. Update of Tooltip texts accordingly
3. Update of output port labels as Message instead of Email
> google.gmail: Updates for QA

- src/appmixer/utils/converters/CSV2HTML/CSV2HTML.js
- src/appmixer/utils/converters/CSV2JSON/CSV2JSON.js
- src/appmixer/utils/converters/JSON2CSV/JSON2CSV.js
- src/appmixer/utils/converters/JSON2HTML/JSON2HTML.js
- src/appmixer/utils/converters/bundle.json
- src/appmixer/utils/converters/converters.js
- src/appmixer/utils/converters/csvTransforms.js
- src/appmixer/utils/csv/AddRow/component.json
- src/appmixer/utils/csv/AddRows/component.json
- src/appmixer/utils/csv/CreateCSV/component.json
- src/appmixer/utils/csv/bundle.json
fixes related to 
- https://github.com/clientIO/appmixer-connectors/pull/121
- https://github.com/clientIO/appmixer-components/pull/1891
> utils.converters: fixes, [appmixer.utils.csv.CreateCSV] Getting undefined error when Content is blank

- src/appmixer/microsoft/mail/DeletedEmail/DeletedEmail.js
- src/appmixer/microsoft/mail/NewEmail/NewEmail.js
- src/appmixer/microsoft/mail/UpdatedEmail/UpdatedEmail.js
- src/appmixer/microsoft/mail/bundle.json
- src/appmixer/microsoft/mail/commons.js
Fix for: https://github.com/clientIO/appmixer-components/issues/1890
Fixed
> fix microsoft.mail triggers subscription renewal

- src/appmixer/airtable/bundle.json
- src/appmixer/airtable/records/ListBases/ListBases.js
- src/appmixer/airtable/records/ListTables/ListTables.js
Fix for https://github.com/clientIO/appmixer-components/issues/1909.
- ListBases, ListTables
- has to be a breaking change as there is a change in outputPorts
> Airtable: fix outputPortOptions

- src/appmixer/mailchimp/bundle.json
- src/appmixer/mailchimp/campaigns/ListCampaigns/ListCampaigns.js
- src/appmixer/mailchimp/files/ListFiles/ListFiles.js
Fix for https://github.com/clientIO/appmixer-components/issues/1923#issuecomment-2389036071
> Mailchimp: fix `items` array label

- src/appmixer/mailchimp/bundle.json
- src/appmixer/mailchimp/commons.js
> Mailchimp (patch) fix error when exporting empty list into a file

- src/appmixer/quickbooks/bundle.json
- src/appmixer/quickbooks/commons.js
The same problem as in https://github.com/clientIO/appmixer-connectors/pull/216
> Quickbooks (patch) fix error when exporting empty list into a file

- src/appmixer/mailchimp/bundle.json
- src/appmixer/mailchimp/lists/FindSubscriber/FindSubscriber.js
- src/appmixer/mailchimp/lists/FindSubscriber/component.json
for https://github.com/clientIO/appmixer-components/issues/1947#issuecomment-2426116409
> Mailchimp.FindSubscriber (minor) adding notFound port in FindSubscribers

- src/appmixer/utils/ftp/client.js
Fixes https://github.com/clientIO/appmixer-components/issues/1975
> FTP (fix) ftp only connection

- src/appmixer/microsoft/mail/MoveMail/component.json
- src/appmixer/microsoft/mail/bundle.json
updated the tooltip text of move mail component
> Microsoft.Mail. (minor). MoveMail

- src/appmixer/notion/core/NewDatabaseItem/component.json
Found in https://github.com/jirihofman/appmixer-components/actions/runs/11605523247/job/32316069330. Related to https://github.com/clientIO/appmixer-components/pull/1982.
No bundle.json bump, I don't think this requires a new release yet.
> Notion label update

- src/appmixer/utils/csv/CSVProcessor.js
- src/appmixer/utils/csv/bundle.json
Fix for https://github.com/clientIO/appmixer-components/issues/1944
<hr>
> CSV AddRows (patch) - warn when adding empty lines

- src/appmixer/jira/bundle.json
- src/appmixer/jira/issues/UpdatedIssue/UpdatedIssue.js
The error was that I filtered the issues for created vs updated and forgot to then check if the filtered issue array has actually some issues.
Am I correctly updating the bundle.json for it?
> Jira.UpdatedIssue (patch): fix onTick error

- src/appmixer/utils/csv/CreateCSV/component.json
- src/appmixer/utils/csv/bundle.json
Fix for https://github.com/clientIO/appmixer-components/issues/1806
> utils.csv.CreateCSV (patch) description update

- src/appmixer/dropbox/bundle.json
- src/appmixer/dropbox/files/NewFile/NewFile.js
- src/appmixer/dropbox/files/NewFile/component.json
- src/appmixer/dropbox/files/NewFolder/NewFolder.js
- src/appmixer/dropbox/files/NewFolder/component.json
> dropbox.files.NewFile, NewFolder (patch) Add Path and Recursive options.

- src/appmixer/docusign/bundle.json
follow-up for the https://github.com/clientIO/appmixer-connectors/pull/235 (bump version)
> Docusign (patch) fix auth

- src/appmixer/virustotal/auth.js
- src/appmixer/virustotal/bundle.json
- src/appmixer/virustotal/icon.svg
- src/appmixer/virustotal/ioc/ScanURL/ScanURL.js
- src/appmixer/virustotal/ioc/ScanURL/component.json
- src/appmixer/virustotal/quota.js
- src/appmixer/virustotal/service.json
> virustotal (new)

- src/appmixer/utils/tasks/RequestApprovalEmail/RequestApprovalEmail.js
- src/appmixer/utils/tasks/bundle.json
- src/appmixer/utils/tasks/package.json
Fixes https://github.com/clientIO/appmixer-components/issues/1999
> utils.tasks.RequestApprovalEmail (patch) switch from mandrill to mailchimp API

- src/appmixer/pipedrive/bundle.json
- src/appmixer/pipedrive/crm/CreateActivity/component.json
- src/appmixer/pipedrive/crm/CreateOrganization/component.json
- src/appmixer/pipedrive/crm/CreatePerson/component.json
- src/appmixer/pipedrive/crm/FindDeal/FindDeal.js
- src/appmixer/pipedrive/crm/FindDeal/component.json
- src/appmixer/pipedrive/crm/FindOrganization/FindOrganization.js
- src/appmixer/pipedrive/crm/FindOrganization/component.json
- src/appmixer/pipedrive/crm/FindPerson/FindPerson.js
- src/appmixer/pipedrive/crm/FindPerson/component.json
- src/appmixer/pipedrive/crm/FindProduct/FindProduct.js
- src/appmixer/pipedrive/crm/FindProduct/component.json
- src/appmixer/pipedrive/crm/FindUser/FindUser.js
- src/appmixer/pipedrive/crm/FindUser/component.json
- src/appmixer/pipedrive/crm/ListActivities/transformers.js
- src/appmixer/pipedrive/crm/UpdateActivity/component.json
- src/appmixer/pipedrive/searchOutput.js
This update fixes multiple issues and rewrites some components using REST API instead of pipedrive's library:
> pipedrive (minor) components fixes + updates

- src/appmixer/openai/bundle.json
- src/appmixer/openai/core/createCompletion/component.json
- src/appmixer/openai/core/createCompletion/createCompletion.js
- src/appmixer/openai/core/listFiles/component.json
- src/appmixer/openai/core/listFiles/listFiles.js
- src/appmixer/openai/core/listFineTuningEvents/listFineTuningEvents.js
- src/appmixer/openai/core/listModels/listModels.js
- src/appmixer/openai/core/listModels/transform.js
- src/appmixer/openai/core/listPaginatedFineTuningJobs/listPaginatedFineTuningJobs.js
- src/appmixer/openai/core/retrieveModel/component.json
Reverts clientIO/appmixer-connectors#312
> Revert "OpenAI (patch) CreateCompletion, RetrieveModel"

- src/appmixer/servicenow/record/UpdateRecord/component.json
fixes: https://github.com/clientIO/appmixer-components/issues/2040#issuecomment-2556912560
> ServiceNow: fix updateRecord

- src/appmixer/slack/bundle.json
- src/appmixer/slack/lib.js
- src/appmixer/slack/list/SendChannelMessage/component.json
- src/appmixer/slack/list/SendPrivateChannelMessage/component.json
Fix for https://github.com/clientIO/appmixer-components/issues/2050#issuecomment-2647457037
> Slack (patch) add icon and name to bot messages

- src/appmixer/google/drive/DeletedFileOrFolder/DeletedFileOrFolder.js
- src/appmixer/google/drive/DeletedFileOrFolder/component.json
- src/appmixer/google/drive/FindFilesOrFolders/FindFilesOrFolders.js
- src/appmixer/google/drive/FindFilesOrFolders/component.json
- src/appmixer/google/drive/UpdatedFileOrFolder/UpdatedFileOrFolder.js
- src/appmixer/google/drive/UpdatedFileOrFolder/component.json
- src/appmixer/google/drive/bundle.json
- src/appmixer/google/drive/lib.js
- src/appmixer/google/drive/package.json
additional changes for the https://github.com/clientIO/appmixer-connectors/pull/343 
changes are only in this commit: https://github.com/clientIO/appmixer-connectors/commit/176fd7c28d5cf2a5d576b3891709faf3ae46fc90 fixing [this comment ](https://github.com/clientIO/appmixer-connectors/pull/343#pullrequestreview-2572728850)
> google.drive (minor) FindFilesOrFolders now support recursive search

- src/appmixer/pipedrive/bundle.json
- src/appmixer/utils/files/bundle.json
followup 
- https://github.com/clientIO/appmixer-connectors/pull/419
- https://github.com/clientIO/appmixer-connectors/pull/426
> utils.files, pipedrive: bump version
